# Generated by Django 5.2.3 on 2025-06-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DebtSummary",
            fields=[
                (
                    "agency_id",
                    models.IntegerField(
                        db_column="agency_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "agency_name",
                    models.CharField(db_column="agency_name", max_length=255),
                ),
                (
                    "debt_amount",
                    models.DecimalField(
                        db_column="debt_amount", decimal_places=2, max_digits=15
                    ),
                ),
            ],
            options={
                "db_table": "v_debt_summary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SalesMonthly",
            fields=[
                (
                    "month",
                    models.CharField(
                        db_column="month",
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        db_column="total_sales", decimal_places=2, max_digits=15
                    ),
                ),
            ],
            options={
                "db_table": "v_sales_monthly",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_id",
                    models.AutoField(
                        db_column="payment_id", primary_key=True, serialize=False
                    ),
                ),
                ("payment_date", models.DateField(db_column="payment_date")),
                ("agency_id", models.IntegerField(db_column="agency_id")),
                ("user_id", models.IntegerField(db_column="user_id")),
                (
                    "amount_collected",
                    models.DecimalField(
                        db_column="amount_collected", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_column="created_at", null=True),
                ),
            ],
            options={
                "db_table": "payment",
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["agency_id"], name="payment_agency__bba8c1_idx"
                    ),
                    models.Index(fields=["user_id"], name="payment_user_id_aa0b64_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "report_id",
                    models.AutoField(
                        db_column="report_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("sales", "Sales"), ("debt", "Debt")],
                        db_column="report_type",
                        max_length=50,
                    ),
                ),
                ("report_date", models.DateField(db_column="report_date")),
                ("data", models.JSONField(db_column="data")),
                ("created_by", models.IntegerField(db_column="created_by")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_column="created_at", null=True),
                ),
            ],
            options={
                "db_table": "report",
                "ordering": ["-report_date"],
                "indexes": [
                    models.Index(
                        fields=["report_type"], name="report_report__a84470_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="report_created_304dc3_idx"
                    ),
                ],
            },
        ),
    ]
