# Generated by Django 5.2.3 on 2025-06-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False, 'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': False, 'ordering': ['-report_date']},
        ),
        migrations.AlterModelTable(
            name='debtsummary',
            table='finance"."v_debt_summary',
        ),
        migrations.AlterModelTable(
            name='salesmonthly',
            table='finance"."v_sales_monthly',
        ),
    ]
