# Generated by Django 5.2.3 on 2025-06-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_payment_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE SCHEMA IF NOT EXISTS finance;

            CREATE TABLE IF NOT EXISTS "finance"."payment" (
                payment_id SERIAL PRIMARY KEY,
                payment_date DATE NOT NULL,
                agency_id INTEGER NOT NULL,
                user_id INTEGER NOT NULL,
                amount_collected NUMERIC(15, 2) NOT NULL,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS "finance"."report" (
                report_id SERIAL PRIMARY KEY,
                report_type VARCHAR(50) NOT NULL,
                report_date DATE NOT NULL,
                data JSONB NOT NULL,
                created_by INTEGER NOT NULL,
                created_at TIMESTAMPTZ DEFAULT NOW()
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS "finance"."report";
            DROP TABLE IF EXISTS "finance"."payment";
            DROP SCHEMA IF EXISTS finance;
            """
        )
    ]
