# Generated by Django 5.2.3 on 2025-07-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_create_finance_schema"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="debtsummary",
            table='"finance"."v_debt_summary"',
        ),
        migrations.AlterModelTable(
            name="payment",
            table='"finance"."payment"',
        ),
        migrations.AlterModelTable(
            name="report",
            table='"finance"."report"',
        ),
        migrations.AlterModelTable(
            name="salesmonthly",
            table='"finance"."v_sales_monthly"',
        ),
    ]
