# Generated by Django 5.2.3 on 2025-06-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'managed': False, 'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='issuedetail',
            options={'managed': False, 'ordering': ['issue', 'item']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False, 'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'managed': False, 'ordering': ['-receipt_date']},
        ),
        migrations.AlterModelOptions(
            name='receiptdetail',
            options={'managed': False, 'ordering': ['receipt', 'item']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'managed': False, 'ordering': ['unit_name']},
        ),
    ]
