# Generated by Django 4.2.21 on 2025-07-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_create_inventory_schema"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="issue",
            table='"inventory"."issue"',
        ),
        migrations.AlterModelTable(
            name="issuedetail",
            table='"inventory"."issuedetail"',
        ),
        migrations.AlterModelTable(
            name="item",
            table='"inventory"."item"',
        ),
        migrations.AlterModelTable(
            name="receipt",
            table='"inventory"."receipt"',
        ),
        migrations.AlterModelTable(
            name="receiptdetail",
            table='"inventory"."receiptdetail"',
        ),
        migrations.AlterModelTable(
            name="unit",
            table='"inventory"."unit"',
        ),
    ]
