# Generated by Django 5.2.3 on 2025-06-17 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "account_id",
                    models.AutoField(
                        db_column="account_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "username",
                    models.CharField(db_column="username", max_length=50, unique=True),
                ),
                (
                    "password_hash",
                    models.CharField(db_column="password_hash", max_length=255),
                ),
                (
                    "account_role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("agent", "Agent"),
                        ],
                        db_column="account_role",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_column="created_at", null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "account",
                "ordering": ["username"],
                "indexes": [
                    models.Index(
                        fields=["account_role"], name="account_account_4b8b72_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.CharField(db_column="full_name", max_length=100)),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        db_column="email",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_column="phone_number", max_length=15, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="address", max_length=255, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_column="created_at", null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", null=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="authentication.account",
                    ),
                ),
            ],
            options={
                "db_table": "user",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(fields=["account"], name="user_account_8a8b20_idx")
                ],
            },
        ),
    ]
