# Generated by Django 5.2.3 on 2025-06-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False, 'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'ordering': ['full_name']},
        ),
    ]
