# Generated by Django 5.0.6 on 2024-07-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_account_options_alter_user_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE SCHEMA IF NOT EXISTS auth;
            
            CREATE TABLE IF NOT EXISTS "auth"."account" (
                account_id SERIAL PRIMARY KEY,
                username VARCHAR(50) UNIQUE NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                account_role VARCHAR(20) NOT NULL,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
            
            CREATE TABLE IF NOT EXISTS "auth"."user" (
                user_id SERIAL PRIMARY KEY,
                account_id INTEGER NOT NULL REFERENCES "auth"."account"(account_id) ON DELETE CASCADE,
                full_name VARCHAR(100) NOT NULL,
                email VARCHAR(100) UNIQUE,
                phone_number VARCHAR(15),
                address VARCHAR(255),
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS "auth"."user";
            DROP TABLE IF EXISTS "auth"."account";
            DROP SCHEMA IF EXISTS auth;
            """
        ),
    ]
