# Generated by Django 4.2.21 on 2025-07-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_account_role_check_constraint"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="account",
            table='"auth"."account"',
        ),
        migrations.AlterModelTable(
            name="user",
            table='"auth"."user"',
        ),
    ]
