# Generated by Django 5.2.3 on 2025-06-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulation',
            options={'managed': False, 'ordering': ['regulation_key'], 'verbose_name': 'Regulation', 'verbose_name_plural': 'Regulations'},
        ),
    ]
