# Generated by Django 5.2.3 on 2025-06-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulation', '0002_alter_regulation_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='regulation',
            table='"config"."regulation"',
        ),
    ]
