# Generated by Django 5.2.3 on 2025-06-17 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgencyType",
            fields=[
                (
                    "agency_type_id",
                    models.AutoField(
                        db_column="agency_type_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "type_name",
                    models.CharField(db_column="type_name", max_length=50, unique=True),
                ),
                (
                    "max_debt",
                    models.DecimalField(
                        db_column="max_debt", decimal_places=2, max_digits=15
                    ),
                ),
                ("description", models.TextField(db_column="description", null=True)),
            ],
            options={
                "db_table": "agencytype",
                "ordering": ["type_name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "district_id",
                    models.AutoField(
                        db_column="district_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "city_name",
                    models.CharField(db_column="city_name", max_length=100, null=True),
                ),
                (
                    "district_name",
                    models.CharField(
                        db_column="district_name", max_length=100, unique=True
                    ),
                ),
                ("max_agencies", models.IntegerField(db_column="max_agencies")),
            ],
            options={
                "db_table": "district",
                "ordering": ["city_name", "district_name"],
            },
        ),
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "agency_id",
                    models.AutoField(
                        db_column="agency_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "agency_name",
                    models.CharField(db_column="agency_name", max_length=150),
                ),
                (
                    "phone_number",
                    models.CharField(db_column="phone_number", max_length=15),
                ),
                ("address", models.CharField(db_column="address", max_length=255)),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        db_column="email",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "representative",
                    models.CharField(
                        blank=True,
                        db_column="representative",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("reception_date", models.DateField(db_column="reception_date")),
                (
                    "debt_amount",
                    models.DecimalField(
                        db_column="debt_amount", decimal_places=2, max_digits=15
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_column="created_at", null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_column="updated_at", null=True),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True, db_column="user_id", null=True, unique=True
                    ),
                ),
                (
                    "agency_type",
                    models.ForeignKey(
                        db_column="agency_type_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="agencies",
                        to="agency.agencytype",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        db_column="district_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="agencies",
                        to="agency.district",
                    ),
                ),
            ],
            options={
                "db_table": "agency",
                "ordering": ["agency_name"],
            },
        ),
        migrations.CreateModel(
            name="StaffAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.IntegerField(db_column="staff_id")),
                (
                    "agency",
                    models.ForeignKey(
                        db_column="agency_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_agency",
                        to="agency.agency",
                    ),
                ),
            ],
            options={
                "db_table": "staffagency",
                "ordering": ["staff_id", "agency"],
            },
        ),
        migrations.AddIndex(
            model_name="agency",
            index=models.Index(
                fields=["agency_type"], name="agency_agency__32d6a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agency",
            index=models.Index(fields=["district"], name="agency_distric_e5bc9f_idx"),
        ),
        migrations.AddConstraint(
            model_name="staffagency",
            constraint=models.UniqueConstraint(
                fields=("staff_id", "agency"), name="unique_staff_agency"
            ),
        ),
    ]
