# Generated by Django 5.2.3 on 2025-06-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'managed': False, 'ordering': ['agency_name']},
        ),
        migrations.AlterModelOptions(
            name='agencytype',
            options={'managed': False, 'ordering': ['type_name']},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'managed': False, 'ordering': ['city_name', 'district_name']},
        ),
        migrations.AlterModelOptions(
            name='staffagency',
            options={'managed': False, 'ordering': ['staff_id', 'agency']},
        ),
    ]
