# Generated by Django 5.2.3 on 2025-06-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_agency_options_alter_agencytype_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE SCHEMA IF NOT EXISTS agency;

            CREATE TABLE IF NOT EXISTS "agency"."agencytype" (
                agency_type_id SERIAL PRIMARY KEY,
                type_name VARCHAR(50) UNIQUE NOT NULL,
                max_debt NUMERIC(15, 2) NOT NULL,
                description TEXT
            );

            CREATE TABLE IF NOT EXISTS "agency"."district" (
                district_id SERIAL PRIMARY KEY,
                city_name VARCHAR(100),
                district_name VARCHAR(100) UNIQUE NOT NULL,
                max_agencies INTEGER NOT NULL
            );

            CREATE TABLE IF NOT EXISTS "agency"."agency" (
                agency_id SERIAL PRIMARY KEY,
                agency_name VARCHAR(150) NOT NULL,
                agency_type_id INTEGER NOT NULL REFERENCES "agency"."agencytype"(agency_type_id) ON DELETE RESTRICT,
                phone_number VARCHAR(15) NOT NULL,
                address VARCHAR(255) NOT NULL,
                district_id INTEGER NOT NULL REFERENCES "agency"."district"(district_id) ON DELETE RESTRICT,
                email VARCHAR(100) UNIQUE,
                representative VARCHAR(100),
                reception_date DATE NOT NULL,
                debt_amount NUMERIC(15, 2) NOT NULL,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW(),
                user_id INTEGER UNIQUE
            );

            CREATE TABLE IF NOT EXISTS "agency"."staffagency" (
                staff_id INTEGER PRIMARY KEY,
                agency_id INTEGER NOT NULL REFERENCES "agency"."agency"(agency_id) ON DELETE CASCADE,
                UNIQUE (staff_id, agency_id)
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS "agency"."staffagency";
            DROP TABLE IF EXISTS "agency"."agency";
            DROP TABLE IF EXISTS "agency"."district";
            DROP TABLE IF EXISTS "agency"."agencytype";
            DROP SCHEMA IF EXISTS agency;
            """
        )
    ]
