# Generated by Django 4.2.21 on 2025-07-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_create_agency_schema"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="agency",
            table='"agency"."agency"',
        ),
        migrations.AlterModelTable(
            name="agencytype",
            table='"agency"."agencytype"',
        ),
        migrations.AlterModelTable(
            name="district",
            table='"agency"."district"',
        ),
        migrations.AlterModelTable(
            name="staffagency",
            table='"agency"."staffagency"',
        ),
    ]
